name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js from .tool-versions
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: "npm"
      - run: npm ci
      - run: npm run typecheck
      - run: npm run format:check
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - name: Generate coverage report
        run: mkdir -p coverage && touch coverage/lcov.info && nyc report --reporter=text-lcov > coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
